version: '3'
services:
  server:
    image: babel-node-test-image
    volumes:
      - .:/usr/src/app/home_automation_server
    working_dir: /usr/src/app/home_automation_server
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - servernet
    command: ["yarn", "start"]
    tty: true
networks:
  servernet:
